var GAME_LEVELS = [
  ["o                                                                            x     ",
   "x          x!xxx!x                                                           x     ",
   "x          xv   vx                                                           x     ",
   "x          x  o  x                                                     o     x     ",
   "x  m       !     x                 xxxx!!!!xxxx                        xx    x     ",
   "!=         !  o  x                 x   v  v !          xx  y   xx    x!!x    x     ",
   "x  y       !     x                 x        x             y        x!!!!x    x     ",
   "xx         x     x          yyyy                          x!!!!!!!!!!!!xx    x     ",
   "x             x  x                      o               xxxxxxxxxxxxxxxxx  x x     ",
   "x                x                              o                        x   x     ",
   "x       o o                       o                                     ox   x     ",
   "!      xxxxxx              o        x         xxxxxx                     x   x     ",
   "! @             xxxx     x!x        x                                  xxx   x     ",
   "xxxo              ox     xo                  o o o  x                   !    x     ",
   "  xx=             oxhxx!!x   x!!!!xzzzzzxzzzzzzzzzzzx x       x!!x      !  o x     ",
   "  x          xxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxx     xxxxxxxx |xxxxxxxxxx     ",
   "  x!!!!!!!!!!x                                             x     xh!!x             ",
   "  x!!!!!!!!!!x   o             o o o           o  o  o     x     xxxxx             ",
   "  xxxxxxxxxxxx         o   o                               x                       ",
   "                                             oxxxxxxxxx!!xxx                       ",
   "     x x         x             xxxxx        xx        xxxx                         ",
   "                    xxxx  xxxhx    xxx|    xxx                                     ",
   "     x x                            x!!!xxxxxx                                     ",
   "     x!x                            x!!!!xxxxx                                     ",
   "                                                                                   "],
  ["                                      x!!x   o       o ox                                                    x!x  ",
   "                                      x!!x   z     xxxxxx                                                    x!x  ",
   "                           o o        x!!x              x     xxxxx!!!!!xxxxx                                x!x  ",
   "                                      x!!!!!!!!!x            xx    !!!!!    xx                               x!x  ",
   "                          xxxxxxx     xxxxxxxxxxx m xxxxxxxxxx  o  !!!!!  o                       o   o   o  x!x  ",
   "           o                    xx         v                       !!!!!              xx                    xx!x  ",
   " o                               x                                 !!!!!                         yyyyyyyyyyyx!!x  ",
   "!x         x            zz       x                x  o        xxxxx!!!!!    o                   !!!!!!!! !!!!!xx  ",
   "!x    o                       o  x                                 !!!!!    x                               !!x   ",
   "!x   xx!!!!!!!!!x                x         xx            x         !!!!!   xx            v             o o  !!x   ",
   "!x   x!!!!!!!!!x x o          x  x                             xxxx!!!!!xxxx      h                         !!x   ",
   "!x   x!!!!!!!xx   xx            xx                   x            xxxxxxx        xxx         xxx            !!x   ",
   "!x   xxxxxxxxx  o  xx           xx       x!!!!!!!!!!!x                                       xx             !!xxxx",
   "            x!x    xxx          x                                          o  x              x          o   !!!!!!",
   "            x!x      x  o    xxx      x                          o                           x              xx!!!!",
   "                     xxxx                  zzzzxx            o       z     o                 x               x!!xx",
   "                               o               x          o      x       x                   x        xxxxx   !!  ",
   "                              xxx              x             x           x o   o             x   x    x o x   !!  ",
   "     o  yy  x!xx                x     o        x          x              x   xxxxxxxxx       x            x   !!  ",
   "             x              x   x!!!!xx        x                         x y x           x   x           xx   !!  ",
   "   @         x                  x              x     yyy                 x!!!x               x                !!  ",
   "             x            yy    x              x                         xxxxx   xxxxxx      x                !!  ",
   " o           x         h        x              x                           o     x!!!        x        x       !!  ",
   "!xxx x!!!!!!!xxxxx!!xxxx!!!!!!xxo    xx!!!!!!!!xx    x!!!!!!!!!!           =     x!!!        x                !!  ",
   "!!!x  x!!!!!!x    o    x!!!!!x                       x!!!!!!!x!!         xxxxxxxxxxxx  o o  xx                !!  ",
   "!!!x   xxxxxx          x!!!!!x    xx     o o o      xx!!!!!!xx!!                           xxx                !!  ",
   "!!!xx                  x!!!!!x    x                xx!!!!!!xx !!              o     xxyyyyyxxx                !!  ",
   "!!!!x    o        o    x!!!!!x         xxxxxxxxxxxxx!!!!!!xx  !!                                              !!  ",
   "!!!!xxxxxxxxxx  zzzz   x!!!!!!         o!!!!!!!!!!!!!!!!!xx   !!                                              !!  ",
   "!!!!!!!!!!!!!x!!!!!!!!!x!!!!!!!!x!!!!xxx!!!!!!!!!!!!!!!!xx!!!!!!!!x!!!!!x!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                       x!x                                                                    ",
   "!!x             o                      x!x                                                                    ",
   "!!!xx                                   v                                                               o     ",
   "!!!!!xx                                                                                                       ",
   "!!!!!!!xx                                                                                               x     ",
   "!!!!!!!!!xx        x    x    xxxxxx     o                                     o                               ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                   x                                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xx                                                            ",
   "    x                                                    x                                 o xxxxxxxxxxxxxxxxx",
   "    x        o       o       o          o                       x                   x     x                   ",
   "    x                                                                       o             x        o          ",
   "    x                               x!!   !!x                                              xxxxxxxxxxxxx      ",
   "    x                               x!! o !!x         xxx        o         xxx                         x      ",
   "    x                             o x!!   !!x           xx             x                      o  o   xx    o  ",
   "    xo       x!!xx!!!xx!!xx!!x      xxx o xxx             xx    o o    x                  xxxxxxxxxxxx        ",
   "    x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x                 x   yyyy   x                  x                   ",
   "    xxx                               x o x                 x!!!!!!!!!!x            xxx!!!x           o       ",
   "                                 =    x   x  o  h   o       xxxxxxxxxxxx            x xxxxxx o xxxxxxxxxxxxxxx",
   "                                      x o x   xxx            x                      x                         ",
   "                o                     x   x   x         xxxxxx                      x                o        ",
   "                                      x o x   x           xxxx                    xxx        x       z        ",
   "                                      x   x   x           o xx                   x                            ",
   "      !xx                             x o x o x       xxxxxxxx        xxxxxxxxxxxx                            ",
   "                         xxxxx        x   x   x       x                                o                 x    ",
   "                             x          o x   x       x           x!!!!!!                    o      m         ",
   "                             x            x   xx      x           xxxxx!!                                     ",
   "               zzz           xxxxx        x!!!!xo     x             o x!!    o         x            x         ",
   "                             x       x    xx          x               x!!                                     ",
   " =                           x!!!!!!!xxxx!xx          x      y        x!!                     x               ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!xxxxxx!!x         h                          ",
   "                             xxxxx  o  xxxxx    y!!!!!x!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x     ",
   "       xxxxxxxxxxxxxxxxxxx!!!xx            x   xxxxxxxxxxxxxxxxxxxxxxxx                                 x  o  ",
   "   @                     x x xx            x                        x                                   x     ",
   "  xxx         o      o   x    x     x      x                        x o                                 xxxxxx",
   "  xo                     x o  x     x       x             o         xxxxxx            xxxxxxxxxxxxxxxxxxxxxx  ",
   "  x    xxxxxxxxxxxxxxxxxxx    x     x       xxxxx                        xxxx         x         x!x        x  ",
   "  x                           x     x                                    x            x          v         x  ",
   "  x=      o          o     o  x     x                                    x            x                    x  ",
   "  xxxxxxxxxxx    xxxxxxxxxxxxxx  y  x             |yyyy|    |yyyy|        x o     x o x                    x  ",
   "  x                                 x  y  x                               x                      o         x  ",
   "  x    o             o              x!!!!!xx         o         o        x x                      x         x  ",
   "  x                                 xxxxxxxxx                           x x         yyyyyy      xxx        x  ",
   "  x                           xxx xxx     xxxx    x    x    x    x     xxoxx     x         x               x  ",
   "!!xzzz!!zzzzzzzzzzzz!!zzzzzzzzx             xxx!!!x!!!!x!!!!x!!!!x!!!xxxyyyxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx          o   xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxx                           xxxxxxh       xx                        x!!!!!x                                 ",
   "                                    xxx!!x!!xx                                                                "],
  ["                                                                                                              ",
   "                                                                                                    o         ",
   "                                                                                                   xxxx       ",
   "                                                                                                  x           ",
   "                                          o                                                       x xxx       ",
   "                          o                                                              xx       o o x    o  ",
   "                                          o                   xoooooo!                            o o x       ",
   "   o           xxxxxxxxxx                                     !x    x!x                               x       ",
   "               x oooooo x                            x        !!!xx!!!!!x                   xxx!!xxxxxx        ",
   "xxxxxxxx       x oooooo x                                              !            x       !   x          o  ",
   "v      x       ! oooooo !              yyyyyyy                       o !      x  o  x    o  !xx x xxxxx       ",
   "       x   x   !!x    x!x                                              !      !     x       ! x x   o x       ",
   "       !               xx o                                  xxxx xxxxx!      !!xxxxxx!xx!xxxxx xxxxxxxxxxxo  ",
   "    xx!!            x   x                 xxxxxx                xmx    !    x           !!  v       x    xxx  ",
   "    x                   xx|x!!x      o    x    x          xx           !                !!        xx    xx    ",
   "    x                        !x               ox                       !             o  !!      xx     xx     ",
   "    x    o      z            x!                x                       x  o             !!            xx      ",
   "    x       x                x!               xx      xx               !!xxxx!       x  !!           xx   o   ",
   "    x               xxx      x!                                                     xxx !!    x     x         ",
   "    x                        x!                               o                   xx o xx       x    xx       ",
   "  o x                     o  xxxxxxxxxxxxxxxxxxxxxx                             x         x     xx    xx!!  !!",
   "  x xx                                         o  x       xx     xx            xx   oooo  xx o    xx          ",
   "  x x       xxxx         xxx          o           x                      x   x xx         xx xx    x       x  ",
   "  x x      xx              x!!!!!!!!    !!!xx  x  x                                  o        x!!!!!xx        ",
   "  x x!!!o !!x                      x        x     x              ||                  x        xxxxxxxxx   o   ",
   "  x xxxxxxxxx                               x     x              o                                            ",
   "  x             xxxxxxxxx            xxxxxxxx     x       o           x                          o    o   o   ",
   "                x       !            xo x         x       ||                  x     x                         ",
   "   @            x       !   o       xx xx         x                                       x  xxxxxxxxxxxxxxxxx",
   "  xxxxxxx      x    o   x                     xxxxx       xx     xx      h                                    ",
   "        x=    x             =                =x   x                     xxx                                   ",
   "!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "               w   w     www     w   w      w           w   w   ww    w   w                             x     ",
   "                w w     w   w    w   w       w         w        w w   w   w                             x     ",
   "                 w      w   w    w   w        w   w   w     w   w   w w   w                             x     ",
   "                 w      w   w    w   w         w w w w      w   w    ww                                 x     ",
   "                 w       www      www           w   w       w   w     w   w                             x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   " @zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxx     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
 ];



if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
